ALTER TYPE "ActivityType" ADD VALUE 'CALL_RECORDING_RECEIVED';
ALTER TYPE "ActivityType" ADD VALUE 'CALL_TRANSCRIPT_READY';
ALTER TYPE "ActivityType" ADD VALUE 'CALL_TRANSCRIPT_FAILED';

ALTER TYPE "TranscriptProcessingStatus" ADD VALUE 'PROCESSING';
