ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'GOTO_CONNECT_SETTINGS_UPDATED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'GOTO_CONNECT_LINE_MAPPING_UPDATED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'GOTO_CONNECT_LINE_MAPPINGS_RERESOLVED';
